(() => {
"use strict";
const C=window.DASHBOARD_CONFIG||{}, $=id=>document.getElementById(id); let last=null;
const demo={atualizadoEm:new Date().toISOString(),calendario:[],jira:[],prazos:[],viaturas:[],mensagens:[{mensagem:"Modo demonstração ativo.",tipo:"NORMAL"}],avisos:[]};
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function clock(){let n=new Date();$("clock").textContent=n.toLocaleTimeString("pt-BR");$("date").textContent=n.toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long",year:"numeric"});}
function pd(v){if(!v)return null;let d=new Date(v+"T12:00:00");return isNaN(d)?null:d}
function sd(v){let d=pd(v);if(!d)return"Sem prazo";let t=new Date();t.setHours(0,0,0,0);let n=Math.round((d-t)/86400000);if(n===0)return"Hoje";if(n===1)return"Amanhã";if(n<0)return`${Math.abs(n)}d atrasada`;return d.toLocaleDateString("pt-BR",{day:"2-digit",month:"short"}).replace(".","")}
function calendar(events){let n=new Date(),y=n.getFullYear(),m=n.getMonth(),f=new Date(y,m,1),s=new Date(y,m,1-f.getDay());$("calendarMonth").textContent=n.toLocaleDateString("pt-BR",{month:"long",year:"numeric"});let h=["DOM","SEG","TER","QUA","QUI","SEX","SÁB"].map(x=>`<div class="weekday">${x}</div>`).join("");
for(let i=0;i<42;i++){let d=new Date(s);d.setDate(s.getDate()+i);let key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;let ev=(events||[]).filter(e=>{let x=new Date(e.inicio);return !isNaN(x)&&`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`===key}).slice(0,3);h+=`<div class="day ${d.getMonth()===m?"":"outside"} ${d.toDateString()===n.toDateString()?"today":""}"><div class="day-number">${d.getDate()}</div>${ev.map(e=>`<span class="event" title="${esc(e.titulo)}">${esc(e.titulo)}</span>`).join("")}</div>`}$("calendar").innerHTML=h}
function jira(items){$("jiraCount").textContent=`${(items||[]).length} abertas`;$("jiraBody").innerHTML=(items||[]).slice(0,9).map(x=>{let p=(x.prioridade||"").toLowerCase(),cl=p.includes("alta")||p.includes("high")?"p-high":p.includes("média")||p.includes("medium")?"p-medium":"p-low";return`<tr class="${cl} ${x.atrasada?"overdue":""}"><td>${esc(x.responsavel||"Não atribuído")}</td><td>${esc(x.espaco||x.espacoChave||"—")}</td><td>${esc(x.tarefa)}</td><td>${esc(sd(x.prazo))}</td></tr>`}).join("")||`<tr><td colspan="4"><div class="empty">Nenhuma tarefa aberta.</div></td></tr>`}
function vehicles(items){$("vehicleList").innerHTML=(items||[]).slice(0,6).map(x=>`<div class="list-item"><div class="when">${esc(x.inicio||"--:--")}–${esc(x.fim||"--:--")}</div><div class="main"><div class="title">${esc(x.missao||"Reserva")}</div><div class="sub">${esc(x.responsavel||"")} ${x.setor?"• "+esc(x.setor):""}</div></div><span class="badge">${esc(x.status||"")}</span></div>`).join("")||`<div class="empty">Nenhuma reserva para hoje.</div>`}
function deadlines(items){$("deadlineList").innerHTML=(items||[]).slice(0,10).map(x=>`<div class="list-item"><div class="when">${esc(sd(x.prazo))}</div><div class="main"><div class="title">${esc(x.tarefa)}</div><div class="sub">${esc(x.responsavel||"Não atribuído")} • ${esc(x.espaco||x.espacoChave||"")}</div></div><span class="badge">${esc(x.prioridade||"")}</span></div>`).join("")||`<div class="empty">Nenhum prazo cadastrado.</div>`}
function messages(items){$("messageList").innerHTML=(items||[]).slice(0,8).map(x=>`<div class="message ${(x.tipo||"").toLowerCase()}">${esc(x.mensagem)}</div>`).join("")||`<div class="empty">Nenhuma mensagem cadastrada.</div>`}
function render(d){last=d;calendar(d.calendario);jira(d.jira);vehicles(d.viaturas);deadlines(d.prazos);messages(d.mensagens);$("status").textContent=`Atualizado: ${new Date(d.atualizadoEm||Date.now()).toLocaleTimeString("pt-BR")}${(d.avisos||[]).length?" • "+d.avisos.join(" • "):""}`}
function load(){let u=C.API_URL||"";if(!u||u.includes("SUBSTITUIR_")){render(demo);$("status").textContent="Modo demonstração — configure API_URL em config.js";return}let cb="dash_"+Date.now(),sc=document.createElement("script"),tm=setTimeout(()=>{clean();fail("Tempo esgotado ao consultar a API.")},20000);function clean(){clearTimeout(tm);delete window[cb];sc.remove()}function fail(m){if(!last&&C.USE_DEMO_WHEN_UNCONFIGURED)render(demo);$("status").textContent=m}window[cb]=d=>{clean();d&&d.ok!==false?render(d):fail(d&&d.erro?d.erro:"Falha na API.")};sc.onerror=()=>{clean();fail("Não foi possível carregar a API.")};sc.src=u+(u.includes("?")?"&":"?")+`callback=${cb}&t=${Date.now()}`;document.body.appendChild(sc)}
clock();setInterval(clock,1000);load();setInterval(load,Math.max(1,Number(C.REFRESH_MINUTES||3))*60000);
})();